version: '3.8'

services:
  db:
    image: mysql:8.1.0
    # environment:
    #   - MYSQL_ROOT_PASSWORD=root
    #   - MYSQL_DATABASE=app_db
    env_file:
      - ./db/.env
    ports:
      - "3306:3306"
    networks:
      - app-networks
    volumes:
      - db_data:/var/lib/mysql
  server:
    # image: nginx:1.21.3-alpine
    build:
     context: ./server
     dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-networks
  app:
    build:
     context: ./app
     dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    networks:
      - app-networks
    env_file:
      - ./app/.env
    depends_on:
      - db
  db-migrate:
    build:
     context: ./app
     dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    networks:
      - app-networks
    env_file:
      - ./app/.env
    depends_on:
      - db
    profiles:
      - tools
    command: ["python3", "manage.py", "migrate"]
    
networks:
  app-networks:
    driver: bridge

volumes:
  db_data: